### ISSUE TITLE
Если подобрать какой-либо предмет во время ритуала, он остановится, но уже пропавшие предметы не вернутся

### ISSUE THREAD

**Issue by Voladsky** [teachyyou/Ars-Maleficarum-1.20.1#33]
Есть ли возможность при начале ритуала блокировать подбор предметов? Просто их может быть много (как для создания саженца красного дерева), и шанс случайно что-то подобрать.

**Comment by teachyyou** [comment]
Безусловно, это легко (во всяком случае, так мне это представляется) реализовать, и такая мысль была, однако мы решили, что это (возврат предметов в случае неудачи или предотвращение неудачи блоком подбора предметов) будет лишним, поскольку ошибка волшебника во время ритуала должна быть возможна, а кроме того - "наказуема" как минимум потерей уже поглощенных магией предметов, не говоря уже о побочных эффектах, которые мы планируем добавить позже)
