### ISSUE TITLE
Поэкспериментируйте с мелками

### ISSUE THREAD

**Issue by Voladsky** [teachyyou/Ars-Maleficarum-1.20.1#34]
Знаки, символы на стенах - у них могут быть какие-то свойства, они как-то могут влиять на окружение (на дом, например). Мне показалось интересной мыслью, можете подумать, если есть возможность.

**Comment by teachyyou** [comment]
Рисование символов на стенах не является тем, что в данный момент целесообразно реализовывать - мел был добавлен специально для рисования ритуальных кругов и пентаграмм на алтаре, других применений для не предусмотрено. Кроме того, возможность написания новой механики самостоятельных глифов силы сейчас в принципе отсутствовала по причине большого количества других (заранее внесенных в план) фич, требующих исправления, доделывания или добавления.
