### ISSUE TITLE
Шляпа ведьмы - просто фиолетовый куб

### ISSUE THREAD

**Issue by Voladsky** [teachyyou/Ars-Maleficarum-1.20.1#61]
![2024-05-26_16 28 38](https://github.com/teachyyou/Ars-Maleficarum-1.20.1/assets/59023506/c1691d7c-828b-4593-9577-c2bad7729482)

**Comment by teachyyou** [comment]
У вас установлен Geckolib 1.20.1 4.4.4?

**Comment by teachyyou** [comment]
Мы выяснили причину - это из-за Optifine. Вы, вероятно, установили ForgeOptifine, он направлен на "оптимизацию" и затрагивает рендер, а потому рендер шляпы мог сломаться. Просим перейти на просто 1.20.1 Forge

**Comment by teachyyou** [comment]
Created an issue for general Optifine conflict fixing
